### ISSUE TITLE
Playlist edit results in HTTP 404

### ISSUE THREAD

**Issue by tobiasjakobi** [rain0r/ampd#464] opened 2023-01-16 18:17 UTC
Hello,

I'm currently looking for a MPD client that has playlist editing functionality. According to the ampd README there seems to be some functionality implemented. It's not working for me though.

Here's a screenshot using FireFox 107 using the interface:
![screenshot_2023-01-16-190521](https://user-images.githubusercontent.com/6507947/212743396-c1505110-feb4-4409-912b-73bd2875e80d.png)

ampd is running inside a docker container on a Gentoo Linux.

The only relevant entry I see in the logs is the following:
```
2023-01-16 18:05:10.182  WARN 1 --- [0.0-8080-exec-2] o.h.ampd.server.service.PlaylistService  : Could not get info about playlist: Best of 2012 (Anime, Other)
```

Does playlist handling maybe not work when running inside a container?

With best wishes,
Tobias

**Comment by rain0r** [comment] 2023-01-16 19:01
Hi Tobias,

what exactly did you do to produce this error? I couldn't reproduce it. Allthough I didn't ran it from inside docker, I don't think this is the cause.

Unfortunately, `ampd` doesn't support much editing functionality for playlists. From within the playlist info dialog, you can add the whole playlist (or single tracks) to the queue and delete the playlist.

From inside `ampd` it's just possible to save the queue as a playlist. Although there are many ways to (automatically) generate playlists (in m3u format)

Thanks for filing this ticket!

**Comment by tobiasjakobi** [comment] 2023-01-16 19:16
Hello Rainer,

thanks for the quick reply. I'm really just clicking on circular info button of the playlist entry (the rightmost thingy).

Sad to hear that playlist editing is limited. I was previously using GMPC which e.g. has the functionality to send a selection of the playqueue to a playlist. As GMPC is abandoned Gentoo has now dropped it from their repository. As I extensively use playlists, I'm looking for something that has a similar feature set. Maybe you have some recommendations?

**Comment by rain0r** [comment] 2023-01-16 21:36
Okay. Just tested it with the docker version of `ampd` and I can display the contents of a playlist named `Best of 2012 (Anime, Other)` without any problems.

Which version of `ampd` are you using? I tested with version 1.6.1.

I just created #465 to keep track of the proposed playlist-editing features. I hope to find time to implement that soon.

Unfortunately I can't recommend you any client, did you already take a look at https://www.musicpd.org/clients/ ?

**Comment by tobiasjakobi** [comment] 2023-01-17 19:12
Hello Rainer,

also using version 1.6.1 here. I have the impression that it's some timeout problem. I've created a testing playlist, containing only 10 items, and this one loads fine. But compared to other clients loading takes an insane amount of time. So extrapolating this to the more than 200 items my usual playlists have, this might be the reason.

Anything else I can debug here?

**Comment by rain0r** [comment] 2023-01-17 21:11
A timeout wouldn't raise a 404 error but you're right, the loading of big playlists can be slow.

There is in fact one more thing you could do. 

Please open the developer toolbar in your browser. In Firefox it's under Tools -> Browser Tools -> Web Developer Tools.

Then switch to the `Network` tab and reload the page. Click on the `i` icon of the playlist `Best of 2012 (Anime, Other)` and select the request in the Web Developer Console. That would be great.
![2023-01-17-22-08-34](https://user-images.githubusercontent.com/675112/213013260-ef2a3679-be42-4b5f-a425-304e8c219de9.png)

See my screenshot as an example. Thanks!

**Comment by tobiasjakobi** [comment] 2023-01-22 21:42
Hi Rainer,

I exported the request as HAR: 
[har.zip](https://github.com/rain0r/ampd/files/10475580/har.zip)

**Comment by tobiasjakobi** [comment] 2023-02-01 21:50
Hello Rainer,

This is querying playlist information from my laptop. So stuff goes over the network. As you can see dumping the playlist in question barely takes any time at all.
```
liquid@leena ~ $ time mpc lsplaylist > lsplaylist.txt

real	0m0.005s
user	0m0.002s
sys	0m0.000s
liquid@leena ~ $ time mpc playlist "Best of 2012 (Anime, Other)" > playlist_dump.txt

real	0m0.013s
user	0m0.006s
sys	0m0.000s
```

I've attached both the lsplaylist output and the dump.
[lsplaylist.txt](https://github.com/rain0r/ampd/files/10561881/lsplaylist.txt)
[playlist_dump.txt](https://github.com/rain0r/ampd/files/10561882/playlist_dump.txt)

**Comment by rain0r** [comment] 2023-02-05 11:29
Hey there,

that is something that I've noticed as well. Listing the content of a playlist is slow on big playlists.

In `javampd`, the framework that `ampd` uses, `MPDPlaylistDatabase#listPlaylistSongs` retrieves the content of a playlist and then sends a search query for each entry: 

https://github.com/finnyb/javampd/blob/develop/src/main/java/org/bff/javampd/playlist/MPDPlaylistDatabase.java#L66

Haven't found a way to circumvent that yet, unfortunately.

Also, it doesn't matter if the files in the playlist are flac, mp3, ... 

Thank you for the dumps!

**Comment by rain0r** [comment] 2023-02-05 12:25
Actually , I found a way to speed up retrieving playlist contents!

You may check out `ampd-1.6.2`.

**Comment by rain0r** [comment] 2023-02-24 20:34
Closing this as I was unable to reproduce the bug.

**Closed by rain0r** 2023-02-24 20:34 UTC
